# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Alic Microsoft Partners 
 steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
Build Strong connection 
Stakeholders competition on azuremax 
promote new brand
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
Alic business Model For Grow Industry 
Stakeholders come